### PR TITLE
Extended syntax for the `has` operator

### PR DESCRIPTION
**Pull request by emina**
[Rendered](https://github.com/cedar-policy/rfcs/blob/chained-has/text/0062-extended-has.md)

### CODE REVIEW

**Review by mwhicks1 — APPROVED** [review]
LGTM

**Review by cdisselkoen — APPROVED** [review]
Looks great, I'm in favor

**Review by andrewmwells-amazon — APPROVED** [review]

**Review by shaobo-he-aws — APPROVED** [review]

**Comment by emina** [comment]
This RFC is entering the Final Comment Period with the intent to accept, which will end on May 21.

**Comment by philhassey** [comment]
I like it.  Thanks!

**Pull request merged**
