### PR TITLE
Port Cedar formalization to Lean (32)

### PR DESCRIPTION
**Pull request by emina**
[Rendered](https://github.com/cedar-policy/rfcs/blob/cedar-lean/text/0032-port-formalization-to-lean.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by andrewmwells-amazon — APPROVED** [review]

**Review by shaobo-he-aws — APPROVED** [review]

**Review by khieta — APPROVED** [review]

**Review by mwhicks1 — APPROVED** [review]

**Review by john-h-kastner-aws — APPROVED** [review]
I think by our convention this should be RFC 32

**Comment by andrewmwells-amazon** [comment]
> I think by our convention this should be RFC 32

Fixed

**Comment by emina** [comment]
> > I think by our convention this should be RFC 32
> 
> Fixed

Thank you!

**Review by cdisselkoen — APPROVED** [review]

**Review by aaronjeline — APPROVED** [review]

**Comment by emina** [comment]
This RFC is entering the final comment period (FCP).

**Review by cdisselkoen — APPROVED** [review]

**Review by aaronjeline — APPROVED** [review]

**Pull request merged**
